[project]
name = "tracklab"
version = "1.2.0"
description = "A modular end-to-end tracking framework for research and development"
readme = "README.md"
authors = [
    { name = "Victor Joos", email = "victorjoosdtb@gmail.com" },
    { name = "Baptiste Standaert", email = "baptiste.standaert@uclouvain.be"},
    { name = "Vladimir Somers", email = "vladimir.somers@uclouvain.be"},
]

requires-python = ">=3.9"
dependencies = [
    "hydra-core>=1.3",
    "lightning>=2.0",
    "pytorch_lightning>=2.0",
    "numpy==1.23.5",
    "ultralytics>=8.0.100",
     "filterpy>=1.4.5",
    "torch>=1.13.1,<2.6",
    "torchvision>=0.14.1,<=0.20.1",
    # "chumpy>0.66",
    "timm>=0.9.12",
    "soccernet>=0.1.53",
    "yt-dlp>=2023.12.30",
    "gdown>=4.7.1",
    "pandas>=2.1.0",
    "matplotlib>=3.9.0",
    "scikit-learn>=1.5.1",
    "rich",
    "tabulate",
    "sn-trackeval>=0.3.0",
    "tracklab-lap",
]

[project.scripts]
tracklab = "tracklab.main:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [".", "plugins/track"]
include = ["tracklab*", "bot_sort*", "bpbreid_strong_sort*", "byte_track*", "deep_oc_sort*", "oc_sort*", "strong_sort*"]
exclude = []