defaults:
  - default

_target_: tracklab.wrappers.ConflabMOT

# IMPORTANT: when changing the dataset, make sure to change the path in the conflab_load_bbox.yaml too
# tracklab/configs/modules/bbox_detector/conflab_load_bbox.yaml
dataset_path: /tudelft.net/staff-umbrella/neon/experiments/VIT003/full_test_data
annotation_path: /tudelft.net/staff-umbrella/neon/experiments/VIT003/full_test_data
eval_set: "val"

track_eval:
  dataset_class: MotChallenge2DBox
  GT_FOLDER: "eval/gt" # Location of GT data
  GT_LOC_FORMAT: '{gt_folder}/{seq}.txt' # '{gt_folder}/{seq}/gt/gt.txt'
  TRACKERS_FOLDER: 'eval/pred' # Trackers location
  TRACKER_SUB_FOLDER: '' # Tracker files are in TRACKER_FOLDER/tracker_name/TRACKER_SUB_FOLDER
  OUTPUT_FOLDER: "eval/results" # Where to save eval results (if None, same as TRACKERS_FOLDER)
  OUTPUT_SUB_FOLDER: '' # Output files are saved in OUTPUT_FOLDER/tracker_name/OUTPUT_SUB_FOLDER
  SPLIT_TO_EVAL: ${dataset.eval_set}
  PRINT_CONFIG: False
  DO_PREPROC: False
  TRACKER_DISPLAY_NAMES: null
  EVAL_SPACE: 'pitch'
